GET http://localhost:8081/member/test
Accept: application/json
Content-Type: application/json

###

GET http://localhost:10001/member/member/sendCode
Content-Type: application/json

{
  "mobile": "13000000011"
}
###

POST http://localhost:10001/member/member/login
Content-Type: application/json

{
  "mobile": "13000000011",
  "code": "1234"
}

<> 2025-06-16T153651.200.json
