server:
  port: 10000
spring:
  cloud:
    gateway:
      routes:
      - id: member
        uri: http://localhost:10001
        predicates:
        - Path=/member/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers:
              - "*"
            exposed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600

