server:
  port: 10000
spring:
  cloud:
    gateway:
      routes:
      - id: member
        uri: http://localhost:10001
        predicates:
        - Path=/member/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:*
            allowedHeaders:*
            allowedMethods:*
            allowCredentials:true
            maxAge:3600

